[workspace]
members = [
    "exercises/*/*",
    "helpers/common",
    "helpers/mdbook-exercise-linker",
    "helpers/ticket_fields",
]
resolver = "2"

[profile.dev]
# overflow-checks = false // Ex 02-08_overflow
